/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
  kotlin("multiplatform") version "1.3.50"
}

repositories {
  mavenCentral()
}

kotlin {
  macosX64("macos") {
    binaries {
      executable {
        entryPoint("script.main")
      }
    }
  }
}
