/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    id("org.jetbrains.kotlin.konan").version("1.3.20")
}

konanArtifacts {
    program("hello_script")
}
